### ISSUE TITLE
ValueError running describe

### ISSUE THREAD

**Issue by remram44** [KnowledgeCaptureAndDiscovery/somef#101]
```console
$ somef describe -r https://github.com/remram44/taguette -o out.json
SOMEF Command Line Interface
Loading Repository https://github.com/remram44/taguette Information....
Repository Information Successfully Loaded. 

Extracting information using headers
Extracting headers and content.
Labeling headers.
Traceback (most recent call last):
  File "/tmp/home/.local/bin/somef", line 33, in <module>
    sys.exit(load_entry_point('somef', 'console_scripts', 'somef')())
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/home/somef/src/somef/__main__.py", line 90, in describe
    cli.run_cli(**kwargs)
  File "/tmp/home/somef/src/somef/cli.py", line 465, in run_cli
    repo_data = cli_get_data(threshold, repo_url=repo_url)
  File "/tmp/home/somef/src/somef/cli.py", line 427, in cli_get_data
    header_predictions, string_list = extract_categories_using_header(unfiltered_text)
  File "/tmp/home/somef/src/somef/cli.py", line 335, in extract_categories_using_header
    header_info, string_list = header_analysis.extract_categories_using_headers(repo_data)
  File "/tmp/home/somef/src/somef/header_analysis.py", line 145, in extract_categories_using_headers
    data['Group'].iloc[0] = ['unknown']
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1802, in _setitem_with_indexer
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 534, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 886, in setitem
    values = values.astype(arr_value.dtype, copy=False)
ValueError: setting an array element with a sequence
```

Packages (on Python 3.6):

```console
$ pip freeze
beautifulsoup4==4.9.1
bs4==0.0.1
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
click-option-group==0.5.1
cycler==0.10.0
idna==2.10
importlib-metadata==1.7.0
isodate==0.6.0
joblib==0.16.0
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.3.2
nltk==3.5
numpy==1.19.2
pandas==1.1.2
Pillow==7.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
rdflib==5.0.0
rdflib-jsonld==0.5.0
regex==2020.7.14
requests==2.24.0
scikit-learn==0.21.2
scipy==1.5.2
six==1.15.0
-e git+https://github.com/KnowledgeCaptureAndDiscovery/somef.git@a822cbbbed7fbfb08e830011a97d037c063d5d2c#egg=somef
soupsieve==2.0.1
textblob==0.15.3
tqdm==4.49.0
urllib3==1.25.10
zipp==3.2.0
```

Some other repos seem to work though.

**Comment by dgarijo** [comment]
@remram44 thanks for trying it out.

I think you ran somef with the wrong flag. `-d` is for pointing to the readme file. I ran `somef describe -r https://github.com/remram44/taguette -o test.json -t 0.8` and it produced the attached json file successfully (although the classifiers got some stuff wrong).

[text.txt](https://github.com/KnowledgeCaptureAndDiscovery/somef/files/5263896/text.txt)

**Comment by dgarijo** [comment]
I will keep this issue open because running somef with the wrong file shouldn't crash the tool.

**Comment by remram44** [comment]
Apologies, that was a bad copy/paste from a later attempt. I do get the error with `-r` (updated description).

Same thing if I download the README and use `-d`:

```console
$ somef describe -d README.rst -o out.json
SOMEF Command Line Interface
Extracting information using headers
Extracting headers and content.
Labeling headers.
Traceback (most recent call last):
  File "/tmp/home/.local/bin/somef", line 33, in <module>
    sys.exit(load_entry_point('somef', 'console_scripts', 'somef')())
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/home/somef/src/somef/__main__.py", line 90, in describe
    cli.run_cli(**kwargs)
  File "/tmp/home/somef/src/somef/cli.py", line 467, in run_cli
    repo_data = cli_get_data(threshold, doc_src=doc_src)
  File "/tmp/home/somef/src/somef/cli.py", line 427, in cli_get_data
    header_predictions, string_list = extract_categories_using_header(unfiltered_text)
  File "/tmp/home/somef/src/somef/cli.py", line 335, in extract_categories_using_header
    header_info, string_list = header_analysis.extract_categories_using_headers(repo_data)
  File "/tmp/home/somef/src/somef/header_analysis.py", line 145, in extract_categories_using_headers
    data['Group'].iloc[0] = ['unknown']
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1802, in _setitem_with_indexer
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 534, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 886, in setitem
    values = values.astype(arr_value.dtype, copy=False)
ValueError: setting an array element with a sequence
```

**Comment by dgarijo** [comment]
Hmm that's odd, I cannot reproduce the error. I will have a look.

**Comment by remram44** [comment]
I ran this on Docker.

<details>
<summary>Full log</summary>

```
$ docker run -ti --rm --user 1000 python:3.6 bash
I have no name!@f0f326784e11:/$ mkdir /tmp/home
I have no name!@f0f326784e11:/$ export HOME=/tmp/home
I have no name!@f0f326784e11:/$ cd
I have no name!@f0f326784e11:~$ git clone https://github.com/KnowledgeCaptureAndDiscovery/somef.git
Cloning into 'somef'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1402 (delta 9), reused 19 (delta 5), pack-reused 1372
Receiving objects: 100% (1402/1402), 41.25 MiB | 6.73 MiB/s, done.
Resolving deltas: 100% (616/616), done.
I have no name!@f0f326784e11:~$ cd somef/
I have no name!@f0f326784e11:~/somef$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///tmp/home/somef
Collecting Click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 471 kB/s 
Collecting click-option-group
  Downloading click_option_group-0.5.1-py3-none-any.whl (11 kB)
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 328 kB/s 
Collecting markdown
  Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 2.5 MB/s 
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Collecting matplotlib
  Downloading matplotlib-3.3.2-cp36-cp36m-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 4.8 MB/s 
Collecting nltk
  Downloading nltk-3.5.zip (1.4 MB)
     |████████████████████████████████| 1.4 MB 9.8 MB/s 
Collecting scikit-learn==0.21.2
  Downloading scikit_learn-0.21.2-cp36-cp36m-manylinux1_x86_64.whl (6.7 MB)
     |████████████████████████████████| 6.7 MB 1.9 MB/s 
Collecting pandas
  Downloading pandas-1.1.2-cp36-cp36m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 9.8 MB/s 
Collecting numpy
  Downloading numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 7.8 MB/s 
Collecting textblob
  Downloading textblob-0.15.3-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 6.8 MB/s 
Collecting rdflib
  Downloading rdflib-5.0.0-py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 5.4 MB/s 
Collecting rdflib-jsonld
  Downloading rdflib-jsonld-0.5.0.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 3.5 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 3.7 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 5.7 MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 6.3 MB/s 
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 8.8 MB/s 
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 13.4 MB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 3.9 MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 2.7 MB/s 
Collecting pillow>=6.2.0
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 9.4 MB/s 
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 6.4 MB/s 
Collecting joblib
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 4.4 MB/s 
Collecting regex
  Downloading regex-2020.7.14-cp36-cp36m-manylinux2010_x86_64.whl (660 kB)
     |████████████████████████████████| 660 kB 7.2 MB/s 
Collecting tqdm
  Downloading tqdm-4.49.0-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 4.1 MB/s 
Collecting scipy>=0.17.0
  Downloading scipy-1.5.2-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 8.1 MB/s 
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 4.5 MB/s 
Collecting isodate
  Downloading isodate-0.6.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 2.7 MB/s 
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Downloading zipp-3.2.0-py3-none-any.whl (5.1 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Building wheels for collected packages: bs4, nltk, rdflib-jsonld
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=9cf76303df674f8018da4fddf29dad502809fdaed3578147ca32ed2e12818f5e
  Stored in directory: /tmp/home/.cache/pip/wheels/19/f5/6d/a97dd4f22376d4472d5f4c76c7646876052ff3166b3cf71050
  Building wheel for nltk (setup.py) ... done
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434675 sha256=10e017e68c250958f27c89dfa6a24c71550652dbde619a92db95ef2b4d150b26
  Stored in directory: /tmp/home/.cache/pip/wheels/de/5e/42/64abaeca668161c3e2cecc24f864a8fc421e3d07a104fc8a51
  Building wheel for rdflib-jsonld (setup.py) ... done
  Created wheel for rdflib-jsonld: filename=rdflib_jsonld-0.5.0-py2.py3-none-any.whl size=15349 sha256=34e9579406e903d43145fe9d34c7d1f1844972159c4d0c006f76cd6b7f9ea7bf
  Stored in directory: /tmp/home/.cache/pip/wheels/e4/72/6e/144dce8b21558be176168b23bd8d7062c21cbbe9596c3926ec
Successfully built bs4 nltk rdflib-jsonld
Installing collected packages: Click, click-option-group, idna, certifi, urllib3, chardet, requests, zipp, importlib-metadata, markdown, soupsieve, beautifulsoup4, bs4, six, cycler, kiwisolver, pyparsing, numpy, pillow, python-dateutil, matplotlib, joblib, regex, tqdm, nltk, scipy, scikit-learn, pytz, pandas, textblob, isodate, rdflib, rdflib-jsonld, somef
  WARNING: The script chardetect is installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py is installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts f2py, f2py3 and f2py3.6 are installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk is installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts csv2rdf, rdf2dot, rdfgraphisomorphism, rdfpipe and rdfs2dot are installed in '/tmp/home/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for somef
Successfully installed Click-7.1.2 beautifulsoup4-4.9.1 bs4-0.0.1 certifi-2020.6.20 chardet-3.0.4 click-option-group-0.5.1 cycler-0.10.0 idna-2.10 importlib-metadata-1.7.0 isodate-0.6.0 joblib-0.16.0 kiwisolver-1.2.0 markdown-3.2.2 matplotlib-3.3.2 nltk-3.5 numpy-1.19.2 pandas-1.1.2 pillow-7.2.0 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 rdflib-5.0.0 rdflib-jsonld-0.5.0 regex-2020.7.14 requests-2.24.0 scikit-learn-0.21.2 scipy-1.5.2 six-1.15.0 somef soupsieve-2.0.1 textblob-0.15.3 tqdm-4.49.0 urllib3-1.25.10 zipp-3.2.0
I have no name!@f0f326784e11:~/somef$ /tmp/home/.local/bin/somef configure
SOMEF Command Line Interface
Authorization []: 
Documentation model file [/tmp/home/somef/src/somef/models/description.sk]: 
Invocation model file [/tmp/home/somef/src/somef/models/invocation.sk]: 
Installation model file [/tmp/home/somef/src/somef/models/installation.sk]: 
Citation model file [/tmp/home/somef/src/somef/models/citation.sk]: 
[nltk_data] Downloading package wordnet to /tmp/home/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
Success
I have no name!@f0f326784e11:~/somef$ /tmp/home/.local/bin/somef describe -r https://github.com/remram44/taguette -o out.json
SOMEF Command Line Interface
Loading Repository https://github.com/remram44/taguette Information....
Repository Information Successfully Loaded. 

Extracting information using headers
Extracting headers and content.
Labeling headers.
Traceback (most recent call last):
  File "/tmp/home/.local/bin/somef", line 33, in <module>
    sys.exit(load_entry_point('somef', 'console_scripts', 'somef')())
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/home/somef/src/somef/__main__.py", line 90, in describe
    cli.run_cli(**kwargs)
  File "/tmp/home/somef/src/somef/cli.py", line 465, in run_cli
    repo_data = cli_get_data(threshold, repo_url=repo_url)
  File "/tmp/home/somef/src/somef/cli.py", line 427, in cli_get_data
    header_predictions, string_list = extract_categories_using_header(unfiltered_text)
  File "/tmp/home/somef/src/somef/cli.py", line 335, in extract_categories_using_header
    header_info, string_list = header_analysis.extract_categories_using_headers(repo_data)
  File "/tmp/home/somef/src/somef/header_analysis.py", line 145, in extract_categories_using_headers
    data['Group'].iloc[0] = ['unknown']
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1802, in _setitem_with_indexer
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 534, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 886, in setitem
    values = values.astype(arr_value.dtype, copy=False)
ValueError: setting an array element with a sequence
I have no name!@f0f326784e11:~/somef$ curl -Lo README.rst https://raw.githubusercontent.com/remram44/taguette/master/README.rst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7296  100  7296    0     0  33777      0 --:--:-- --:--:-- --:--:-- 33777
I have no name!@f0f326784e11:~/somef$ /tmp/home/.local/bin/somef describe -d README.rst -o out.json
SOMEF Command Line Interface
Extracting information using headers
Extracting headers and content.
Labeling headers.
Traceback (most recent call last):
  File "/tmp/home/.local/bin/somef", line 33, in <module>
    sys.exit(load_entry_point('somef', 'console_scripts', 'somef')())
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/home/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/home/somef/src/somef/__main__.py", line 90, in describe
    cli.run_cli(**kwargs)
  File "/tmp/home/somef/src/somef/cli.py", line 467, in run_cli
    repo_data = cli_get_data(threshold, doc_src=doc_src)
  File "/tmp/home/somef/src/somef/cli.py", line 427, in cli_get_data
    header_predictions, string_list = extract_categories_using_header(unfiltered_text)
  File "/tmp/home/somef/src/somef/cli.py", line 335, in extract_categories_using_header
    header_info, string_list = header_analysis.extract_categories_using_headers(repo_data)
  File "/tmp/home/somef/src/somef/header_analysis.py", line 145, in extract_categories_using_headers
    data['Group'].iloc[0] = ['unknown']
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1802, in _setitem_with_indexer
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 534, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 886, in setitem
    values = values.astype(arr_value.dtype, copy=False)
ValueError: setting an array element with a sequence
```
</details>

**Comment by dgarijo** [comment]
Excellent, thanks a lot!

**Comment by dgarijo** [comment]
I have been able to reproduce the error, and will have look as soon as possible (apologies for the delay)

**Comment by dgarijo** [comment]
There was an error in the extraction of headers (the tested repo used the markdown alternate syntax, and now we take it into account too)
