### ISSUE TITLE
Empty repo makes somef fail

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/somef#185]
See this repo: https://github.com/c-martinez/test-tool/

Error when formatting output: 

```
formatting output
Traceback (most recent call last):
  File "/home/dgarijo/Documents/GitHub/somef/env/bin/somef", line 11, in <module>
    load_entry_point('somef', 'console_scripts', 'somef')()
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dgarijo/Documents/GitHub/somef/src/somef/__main__.py", line 108, in describe
    cli.run_cli(**kwargs)
  File "/home/dgarijo/Documents/GitHub/somef/src/somef/cli.py", line 801, in run_cli
    save_codemeta_output(repo_data, codemeta_out, pretty=pretty)
  File "/home/dgarijo/Documents/GitHub/somef/src/somef/cli.py", line 679, in save_codemeta_output
    "datePublished": format_date(release_path(["datePublished"])),
  File "/home/dgarijo/Documents/GitHub/somef/src/somef/cli.py", line 634, in format_date
    date_object = date_parser.parse(date_string)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dgarijo/Documents/GitHub/somef/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 75, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
```

**Comment by dgarijo** [comment]
What fails is the transformation to codemeta
